services:
  backend:
    container_name: terrasimapi
    image: terrasimapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    volumes:
      - .:/app/backend
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    restart: always
